### PR TITLE
Fix: Make fresh request sent when load component fail temporary

### LINKED ISSUE #3: when lazy load components failed temporarily, should send fresh request next time
### current behavior

error in console

error in network

you can see that 0.js only request once even though click multi times, and  it still doesn’t send request after the network is ready. 

### expected behavior
send fresh request when encounter a temporary error. 

can i pull a request to fix this problem， [my solution is here!  :)](https://github.com/diem98/preload/commit/1ee1ea5d5613d80a24f5bd6d0ff6f77f1ba6af0a)

### PR DESCRIPTION
**Pull request by diem98**
Make fresh request sent when load component fail temporary. 

 Closes #3 

This is my first pull request， thanks for review. :)

### CODE REVIEW

**Comment by jviide** [comment]
It seems that your commit isn't linked to your GitHub account (as the commit's avatar image is not yours):

screenshot 2018-12-10 at 14 07 17

Do you want to fix this before merging?

**Comment by diem98** [comment]
i don't know how to fix it because i'm in company.  so i think it doesn't matter :),  I will try to fix this later.

**Comment by jviide** [comment]
Ok. Do you want to fix it before I merge this commit, or shall I just merge it now? Both are ok for me 😊

The commit gets linked if its author email address is associated with your GitHub account. Here's a good StackOverflow answer detailing how to change the author for an existing commit: https://stackoverflow.com/questions/3042437/how-to-change-the-commit-author-for-one-specific-commit/3042512#3042512

To set the email for future commits you can configure your git client. Here's GitHub's documentation about that: https://help.github.com/articles/setting-your-commit-email-address-in-git/

**Comment by diem98** [comment]
just merge it now, and thanks for your advice. :)

**Comment by jviide** [comment]
Will do! Thank you for this pull request 👍

**Comment by jviide** [comment]
Published this as @badrap/preload v0.0.6.

**Pull request merged**
